# permissions for end users to view cfstraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfstrait-viewer-role
rules:
- apiGroups:
  - trait.ghostbaby.com
  resources:
  - cfstraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trait.ghostbaby.com
  resources:
  - cfstraits/status
  verbs:
  - get
